name: giift
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - nltk
  - scikit-learn
  - numpy==1.24.3
  - pandas==2.0.3
  - sentencepiece=0.1.97
  - transformers==4.33.3
  - datasets==2.12.0
  - evaluate==0.4.0
  - tqdm==4.64.1
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - pip:
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - Bottleneck
      - brotlipy==0.7.0
      - certifi==2022.12.7
      - cffi
      - charset-normalizer==3.0.1
      - click
      - clip @ git+https://github.com/openai/CLIP.git@3702849800aa56e2223035bccd1c6ef91c704ca8
      - colorama
      - cryptography
      - dill==0.3.6
      - filelock==3.9.0
      - flit_core
      - frozenlist==1.3.3
      - fsspec==2023.1.0
      - ftfy==6.1.1
      - huggingface-hub==0.16.4
      - idna==3.4
      - joblib
      - lxml==4.9.2
      - mkl-random
      - mkl-service==2.4.0
      - multidict==6.0.4
      - multilingual-clip==1.0.10
      - multiprocess==0.70.14
      - numexpr
      - packaging==23.0
      - Pillow==9.3.0
      - portalocker==2.7.0
      - pyarrow==11.0.0
      - pycocotools==2.0.6
      - pycparser
      - pyOpenSSL
      - PySocks
      - python-dateutil
      - pytz
      - PyYAML==6.0
      - regex==2022.10.31
      - requests==2.28.2
      - responses==0.18.0
      - sacrebleu==2.3.1
      - safetensors==0.3.1
      - six
      - tabulate==0.9.0
      - tokenizers==0.13.2
      - torch-poly-lr-decay @ git+https://github.com/cmpark0126/pytorch-polynomial-lr-decay.git@9251dd7190eccfb1cd08e1ebce52e03cff0cb58a
      - typing_extensions==4.5.0
      - urllib3==1.26.14
      - wcwidth==0.2.6
      - xxhash==3.2.0
      - yarl==1.8.2
      - gdown==5.2.0
      - opendatasets==0.1.22
      - torch_geometric==2.6.0
